### ISSUE TITLE
Representation of Folders Seems to be Ignored on Import

### ISSUE THREAD

**Issue by brianjwilson** [archimatetool/OpenGroupXMLExchange#3]
I'm writing a utility that parses an Excel spreadsheet and writes an OpenGroupXMLExchange file for Archi to import. If I dump out a sample file from Archi with folders in it, I find a representation like this:

```xml
  <organizations>
    <item>
      <label xml:lang="en">Strategy</label>
      <item identifierRef="id-2cb515c6-1f25-4eb4-8942-7979fd137788" />
      <item identifierRef="id-f4301c56-7ce6-4b70-9a73-b305df6bfc9b" />
      <item identifierRef="id-90a0fdcb-6722-4116-b86d-d8ab6cb20410" />
    </item>
    <item>
      <label xml:lang="en">Business</label>
      <item>
        <label xml:lang="en">Business Object Folder</label>
        <item identifierRef="id-f43b2bc6-abef-43f3-972e-5cfc7517f9c1" />
      </item>
      <item identifierRef="id-2165cb38-4580-4a81-a236-e13d5b7f3f18" />
```
When I run my script and experimentally insert a new folder object, my rendered output looks like this:
```xml
	<organizations>
		<item>
			<label xml:lang="en">Views</label>
			<item identifierRef="id-488c0971-8d1f-48b2-9855-a6d2b596d9ff"></item>
		</item>
		<item>
			<label xml:lang="en">Business</label>
			<item>
				<label xml:lang="en">NEW FOLDER</label>
				<item identifierRef="id-c6c22e6041cd47189857918f14a3b4d1452607bc004368e47d304a6a"></item>
			</item>
		</item>
	</organizations>
```
This looks like a good representation of the structure to me, but when I import either file into Archi the folders are not created in either element tree.

Since the construct is included on the export I was surprised to see that it was ignored on the import. Perhaps it is by design, perhaps it is a flaw. 

I do see this comment in the source:

```   
// The idea is to see if we can match any referenced elements/relations into a suitable folder
// and then move them to that folder. At this stage, it's not worth it.
```

Perhaps I should render straight to Archi's XML document format and bypass the exchange format.

**Comment by Phillipus** [comment]
See https://github.com/archimatetool/archi/issues/151

There are some issues:

1. Other ArchiMate tools use completely different folder structures and allow a mixture of concept types. How to map these onto Archi's folder structure?
2. Archi uses fixed top level folders, so your "Views" and "Business" folders would be ignored anyway.

It's still not clear to me what the best implementation would be given that other ArchiMate tools use different structures, or maybe even none at all.

**Comment by brianjwilson** [comment]
Makes sense. I'll either live without the folders or go straight to .archimate if I feel like I need them. Thanks!

**Comment by jbsarrodie** [comment]
Hi, just one comment: an option is to put the name of target folder in a property and then run a jArchi script to create the folder structure.
